---
title: "TEMPLATE Post-Secondary Enrollment, Persistence, and Completion Report TEMPLATE"
author: "Nate Giraldi"
date: "Tuesday, May 05, 2015"
output: html_document
runtime: shiny
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
#### define required libraries ####
require(shiny)
```

```{r, echo = FALSE}
#### change max file size ####
options(shiny.maxRequestSize = 25 * 1024^2)  # 25 mb

#### upload data file ####
shinyApp(
  
  ui = fluidPage(
    
    titlePanel('Upload a National Student Clearinghouse raw data file'),
    
    fileInput('nscInput', 'where\'s your NSC file?', multiple = FALSE, accept = NULL),
    
    mainPanel(
      textOutput('uploadInc'),
      tableOutput('nsc')
      )
  ),
  
  server = function(input, output) {
    
    output$uploadInc <-
      
      renderText({
        
        if(is.null(input$nscInput)) {
          print('nothing uploaded yet') } 

        })
    
    output$nsc <-
      reactive({input$nscInput})
    return(nsc)
      
    },
  
  options = list(height = 500)
)
```

```{r}
# print(nsc())
```